version: '3.8'

services:
  pgsql:
    image: postgres:15-alpine
    container_name: votecraft-pgsql
    environment:
      POSTGRES_DB: votecraft
      POSTGRES_USER: votecraft
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - votecraft-network

volumes:
  postgres_data:
  
networks:
  votecraft-network: